name: simple-pipeline
# a simple pipeline for a python script
on: push

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        

    Build:
        runs-on: ubuntu-latest
        needs: [Test]
