name: simple-pipeline
# a simple pipeline for a python script
on: push

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: run python script
          run: python hello.py

    Build:
        runs-on: ubuntu-latest
        needs: [Test]
        steps:
        - uses: actions/checkout@v4
        - name: create an artifact
          uses: actions/upload-artifact@v4
          with:
            name: hello-script
            path: hello.py

